# Generated by Django 3.2.9 on 2021-11-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(default=1, upload_to='banner/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='auther',
            field=models.CharField(default='Unicon', max_length=60),
        ),
    ]
