# Generated by Django 3.2.9 on 2021-11-21 03:05

from django.db import migrations, models

import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20211110_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usershopadress',
            name='order',
        ),
        migrations.AddField(
            model_name='usershopadress',
            name='complate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usershopadress',
            name='date_order',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.usershopadress'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
