# Generated by Django 3.2.9 on 2021-11-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_orderitem_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usershopadress',
            old_name='name',
            new_name='familya',
        ),
        migrations.AddField(
            model_name='usershopadress',
            name='discription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usershopadress',
            name='ism',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
