# Generated by Django 3.2.9 on 2021-11-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20211121_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershopadress',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
